pages:
  stage: deploy
  script:
  - mkdir .public
  - cp -r * .public
  - mv .public public
  environment:
    name: production
    url: https://hiep.vn
  artifacts:
    paths:
    - public
  only:
  - master
